export const movieShelf = [
    {
        id: 1,
        title: "Harry Potter and the Sorcerer's Stone",
        year: 2001,
        director: "Chris Columbus",
        rating: "PG",
        runtime: "2hr 32min",
        poster: "https://m.media-amazon.com/images/M/MV5BNmQ0ODBhMjUtNDRhOC00MGQzLTk5MTAtZDliODg5NmU5MjZhXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_.jpg",
    },
    {
        id: 2,
        title: "Harry Potter and the Chamber of Secrets",
        year: 2002,
        director: "Chris Columbus",
        rating: "PG",
        runtime: "2hr 41min",
        poster: "https://m.media-amazon.com/images/M/MV5BMjE0YjUzNDUtMjc5OS00MTU3LTgxMmUtODhkOThkMzdjNWI4XkEyXkFqcGdeQXVyMTA3MzQ4MTc0._V1_.jpg",
    },
    {
        id: 3,
        title: "Harry Potter and the Prisoner of Askaban",
        year: 2004,
        director: "Alfonso Carón",
        rating: "PG",
        runtime: "2hr 19min",
        poster: "https://cdn.europosters.eu/image/1300/art-photo/harry-potter-the-prisoner-of-azkaban-i105075.jpg",
    },
    {
        id: 4,
        title: "Harry Potter and the Goblet of Fire",
        year: 2005,
        director: "Mike Newell",
        rating: "PG-13",
        runtime: "2hr 37min",
        poster: "https://i0.wp.com/baddogposters.com/wp-content/uploads/2023/02/xl23harrypottergobletoffireptr11041301.jpg?fit=707%2C1000&ssl=1",
    },
    {
        id: 5,
        title: "Harry Potter and the Order of the Phoenix",
        year: 2007,
        director: "David Yates",
        rating: "PG-13",
        runtime: "2hr 18min",
        poster: "https://m.media-amazon.com/images/M/MV5BOTA3MmRmZDgtOWU1Ny00ZDc5LWFkN2YtNzNlY2UxZmY0N2IyXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
    },
    {
        id: 6,
        title: "Harry Potter and the Half-Blood Prince",
        year: 2009,
        director: "David Yates",
        rating: "PG",
        runtime: "2hr 33min",
        poster: "https://m.media-amazon.com/images/I/71f2+J-UVTL._AC_UF894,1000_QL80_.jpg",
    },
    {
        id: 7,
        title: "Harry Potter and the Deathly Hallows: Part 1",
        year: 2010,
        director: "David Yates",
        rating: "PG-13",
        runtime: "2hr 26min",
        poster: "https://m.media-amazon.com/images/I/718wNNc8IcL.jpg",
    },
    {
        id: 8,
        title: "Harry Potter and the Deathly Hallows: Part 2",
        year: 2011,
        director: "David Yates",
        rating: "PG-13",
        runtime: "2hr 10min",
        poster: "https://m.media-amazon.com/images/I/717E6RcrE9L.jpg",
    }
]
